theme = "FixIt"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Blog"
    url = "/posts/"
    title = "Blog"
    weight = 1
    [menu.main.params]
      # add css class to a specific menu item
      class = "text-center"
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-archive"
      # FixIt 0.2.16 | NEW set menu item type, optional value: ["mobile", "desktop"]
      type = ""
  [[menu.main]]
    identifier= "about"
    name = "About"
    url = "/about/"
    title = "About"
    weight = 1
    [menu.main.params]
      # add css class to a specific menu item
      class = "text-center"
      # whether set as a draft menu item whose function is similar to a draft post/page
      draft = false
      # FixIt 0.2.16 | NEW add fontawesome icon to a specific menu item
      icon = "fa-solid fa-address-card"
      # FixIt 0.2.16 | NEW set menu item type, optional value: ["mobile", "desktop"]
      type = ""
    
[params]
  version = "0.2.X"
  description = "Hashem's Personal Website"
  keywords = ["personal", "website","hashem","hashem alayan"]
  defaultTheme = "auto"
  gitRepo = ""
  fingerprint = ""
  dateFormat = "2006-01-02"
  images = []
  enablePWA = false
  externalIcon = false
  disableThemeInject = false

  [params.app]
    title = "Hashem Alayan"
    noFavicon = false
    svgFavicon = ""
    iconColor = "#5bbad5"
    tileColor = "#da532c"
    [params.app.themeColor]
      light = "#f8f8f8"
      dark = "#252627"

  [params.search]
    enable = false
    

  [params.header]
    desktopMode = "sticky"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "Hashem Alayan"
      pre = ""
      post = ""
      typeit = false
    [params.header.subtitle]
      name = ""
      typeit = false

  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2022
    wordCount = true
    license = 'Hashem Alayan'

  [params.section]
    paginate = 20
    dateFormat = "01-02"
    rss = 10
    [params.section.recentlyUpdated]
      enable = false
      rss = false
      days = 30
      maxCount = 10

  [params.list]
    paginate = 20
    dateFormat = "01-02"
    rss = 10

  [params.home]
    
    [params.home.profile]
      enable = true
      gravatarEmail = "hashem.olayano@gmail.com"
      avatarURL = ""
      title = "Hashem Alayan"
      subtitle = "Welcome to my personal page!"
      typeit = true
      social = true
    
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
    GitHub = "hashem78"
    Linkedin = "hashem-alayan"
    Twitter = "hashem_alayan"
    Facebook = "hashem.olayano"
    Telegram = "hashem_alayan"
    Reddit = "mythi55"
    Whatsapp = ""
    Discord = "hhhashem#0262"
    Phone = "+962798609212"
    Email = "hashem.olayano@gmail.com"
    RSS = false

  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = false
    fraction = false
    fontawesome = false
    license = 'Hashem Alayan'
    linkToMarkdown = true
    rssFullText = false
    pageStyle = "normal"
    gravatarForce = false
    [params.page.repost]
      enable = false
      url = ""
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
      position = "right"
    [params.page.expirationReminder]
      enable = false
      reminder = 90
      warning = 180
      closeComment = false
    [params.page.math]
      enable = true
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.code]
      copy = true
      edit = false
      maxShownLines = 10
    [params.page.edit]
      enable = false
      url = ""

    [params.page.share]
      enable = true
      Twitter = true
      Facebook = true
      Linkedin = true
      Reddit = true
    
    [params.page.comment]
      enable = true
      auto = false
      
      [params.page.comment.facebook]
        enable = true
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = true
        dislikes = false
        outlined = false

    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

  [params.mermaid]
    themes = ["neutral", "dark"]

  [params.seo]
    image = ""
    thumbnailUrl = ""

  [params.cookieconsent]
    enable = true
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  [params.cdn]
    data = ""

  [params.gravatar]



  [params.backToTop]
    enable = true
    scrollpercent = false

  [params.readingProgress]
    enable = false
    start = "left"
    position = "top"
    reversed = false
    light = ""
    dark = ""
    height = "2px"
[module]
  [module.hugoVersion]
    extended = true
    min = "0.84.0"
